
version: '3.3'
services:
  main:
    build: .
    ports:
      - '8003:8000'
  face-bokeh-container:
    build: ./face-bokeh
    ports:
      - '8001:8000'

  face-emotion:
    build: ./face-emotion
    ports:
      - '8002:8000'

  triten-container:
    image: 'nvcr.io/nvidia/tritonserver:22.06-py3'
    ports:
      - '8000:8000'
    env_file: .aws.env
    command: ["tritonserver",  "--model-repository=s3://matt-week-05/models/"]

